import type { Hospital } from "@/types/hospital"

// Comprehensive hospital database with coordinates
export const hospitalDatabase: Omit<Hospital, "distance">[] = [
  {
    id: 1,
    name: "مستشفى الشبرا العام",
    address: "شارع الشبرا، القاهرة",
    phone: "+20 123456789",
    lat: 30.0733,
    lng: 31.2453,
    services: ["طوارئ", "جراحة", "أطفال"],
    openHours: "24 ساعة",
    rating: 4.2,
    equipment: ["جهاز تنفس صناعي", "أشعة مقطعية", "غرفة عمليات متقدمة", "وحدة عناية مركزة"],
    trafficFactor: 0.8, // 1.0 is normal traffic, higher means more congestion
  },
  {
    id: 2,
    name: "مستشفى دار الشفاء",
    address: "شارع رمسيس، القاهرة",
    phone: "+20 123456788",
    lat: 30.0614,
    lng: 31.2468,
    services: ["طوارئ", "باطنة", "قلب"],
    openHours: "24 ساعة",
    rating: 4.5,
    equipment: ["جهاز قلب متقدم", "قسطرة قلبية", "أشعة مقطعية", "وحدة عناية مركزة"],
    trafficFactor: 1.2,
  },
  {
    id: 3,
    name: "مستشفى المهابة",
    address: "شارع النيل، القاهرة",
    phone: "+20 123456787",
    lat: 30.0444,
    lng: 31.2357,
    services: ["طوارئ", "عظام", "أعصاب"],
    openHours: "24 ساعة",
    rating: 3.9,
    equipment: ["جهاز رنين مغناطيسي", "أشعة سينية", "جهاز تخطيط أعصاب"],
    trafficFactor: 0.7,
  },
  {
    id: 4,
    name: "المستشفى القبطي",
    address: "شارع كليوباترا، القاهرة",
    phone: "+20 123456786",
    lat: 30.058,
    lng: 31.2145,
    services: ["طوارئ", "نساء وتوليد", "أطفال"],
    openHours: "24 ساعة",
    rating: 4.0,
    equipment: ["جهاز موجات فوق صوتية", "حضانات أطفال", "وحدة عناية مركزة للأطفال"],
    trafficFactor: 0.9,
  },
  {
    id: 5,
    name: "مستشفى سيد جلال",
    address: "شارع الهرم، الجيزة",
    phone: "+20 123456785",
    lat: 30.0131,
    lng: 31.2089,
    services: ["طوارئ", "جراحة", "عيون"],
    openHours: "24 ساعة",
    rating: 3.7,
    equipment: ["جهاز ليزر للعيون", "أشعة مقطعية", "غرفة عمليات"],
    trafficFactor: 1.5,
  },
  {
    id: 6,
    name: "مستشفى السدناوي",
    address: "شارع فيصل، الجيزة",
    phone: "+20 123456784",
    lat: 30.0287,
    lng: 31.2118,
    services: ["طوارئ", "أسنان", "جلدية"],
    openHours: "24 ساعة",
    rating: 4.1,
    equipment: ["وحدة أشعة متكاملة", "معمل تحاليل", "جهاز ليزر جلدي"],
    trafficFactor: 1.3,
  },
  {
    id: 7,
    name: "مستشفى القوات المسلحة",
    address: "شارع العباسية، القاهرة",
    phone: "+20 123456783",
    lat: 30.0728,
    lng: 31.2767,
    services: ["طوارئ", "جراحة", "عناية مركزة"],
    openHours: "24 ساعة",
    rating: 4.6,
    equipment: ["جهاز تنفس صناعي", "أشعة مقطعية", "غرفة عمليات متقدمة", "وحدة عناية مركزة", "جهاز قلب متقدم"],
    trafficFactor: 0.6,
  },
  {
    id: 8,
    name: "مستشفى عين شمس التخصصي",
    address: "شارع الخليفة المأمون، القاهرة",
    phone: "+20 123456782",
    lat: 30.0721,
    lng: 31.2826,
    services: ["طوارئ", "قلب", "كلى"],
    openHours: "24 ساعة",
    rating: 4.3,
    equipment: ["جهاز غسيل كلوي", "قسطرة قلبية", "أشعة مقطعية", "وحدة عناية مركزة"],
    trafficFactor: 1.0,
  },
  {
    id: 9,
    name: "مستشفى الدمرداش",
    address: "شارع العباسية، القاهرة",
    phone: "+20 123456781",
    lat: 30.0772,
    lng: 31.2783,
    services: ["طوارئ", "باطنة", "أطفال"],
    openHours: "24 ساعة",
    rating: 4.0,
    equipment: ["جهاز تنفس صناعي", "حضانات أطفال", "معمل تحاليل متقدم"],
    trafficFactor: 0.9,
  },
  {
    id: 10,
    name: "مستشفى الجلاء التعليمي",
    address: "شارع رمسيس، القاهرة",
    phone: "+20 123456780",
    lat: 30.0561,
    lng: 31.2394,
    services: ["طوارئ", "نساء وتوليد", "أطفال"],
    openHours: "24 ساعة",
    rating: 3.8,
    equipment: ["جهاز موجات فوق صوتية", "حضانات أطفال", "غرفة عمليات"],
    trafficFactor: 1.1,
  },
  {
    id: 11,
    name: "مستشفى الحسين الجامعي",
    address: "شارع الأزهر، القاهرة",
    phone: "+20 123456779",
    lat: 30.0478,
    lng: 31.2629,
    services: ["طوارئ", "جراحة", "عظام"],
    openHours: "24 ساعة",
    rating: 4.2,
    equipment: ["جهاز رنين مغناطيسي", "أشعة سينية", "غرفة عمليات متقدمة"],
    trafficFactor: 1.4,
  },
  {
    id: 12,
    name: "مستشفى قصر العيني",
    address: "شارع القصر العيني، القاهرة",
    phone: "+20 123456778",
    lat: 30.0276,
    lng: 31.2358,
    services: ["طوارئ", "جراحة", "قلب", "أورام"],
    openHours: "24 ساعة",
    rating: 4.7,
    equipment: ["جهاز تنفس صناعي", "أشعة مقطعية", "جهاز علاج إشعاعي", "وحدة عناية مركزة", "جهاز قلب متقدم"],
    trafficFactor: 1.2,
  },
]
